### ISSUE TITLE
无法正确导出QQ里面的图片

### ISSUE THREAD

**Issue by DukeChinatsu** [huiyadanli/PasteEx#1]
复制QQ里面的图片以后，用PasteEX粘贴到文件，保存提示扩展名错误。手动更换其他扩展名之后错误依然存在。

使用环境：
Win10  Pro 1703 x64, OS版本15063.502
已开系统的UAC，不过给了PasteEX管理员权限。

**Comment by huiyadanli** [comment]
已经确认这个问题，估计明天就能修复。

UAC不影响与软件基本功能，只有在添加或删除右键菜单项时会需要管理员权限。。

**Comment by huiyadanli** [comment]
已修复 https://github.com/huiyadanli/PasteEx/commit/527bedb911df2f0be921857adcd57fc339fb13aa
