### ISSUE TITLE
与TotalCommander、ditto等兼容性问题

### ISSUE THREAD

**Issue by gayapple** [huiyadanli/PasteEx#11]
1) 在tc里面按快捷键粘贴无效
2) 开启自动监听保存后， 用了ditto以后小概率会出现直接保存两张图片
3) 在ditto里面切换剪切板内容后, 也会触发自动保存, 这个最好处理下, 毕竟1809的win系统也有剪切板记录功能了
4) 开启了这个软件后, 在windows自带的explorer里面, 复制一个文件, 原地ctrl+v会提示重复, 而不是复制一个附件, 也算是小问题吧
5) 无法启用shift+win+xxx的组合键

**Comment by huiyadanli** [comment]
感谢反馈。
1. 对其他资源管理器类的软件暂时没做适配
2. 关闭自动图片转文件的功能可以解决。
该功能开启时，每当在剪贴版内监听到有图片内容时，会自动往剪切板内追加对应的文件内容，造成剪切板内容变更，会被 ditto 监听到。
3. 同理 ditto 切换剪切板内容后也会造成剪切板内容变更，会被 PasteEx 监听到。后面会添加黑白名单防止同类软件的冲突 #10 
4. 暂时不知道原因，晚上我验证下
5. 暂时不支持直接输入含有 Win 键的组合键，不过可以通过直接修改配置文件来添加此类组合键

**Comment by gayapple** [comment]
测试完美~
