### ISSUE TITLE
监听模式建议

### ISSUE THREAD

**Issue by yu037991** [huiyadanli/PasteEx#12]
建议打开软件自动进入监听模式或者添加一个选项可以打开软件自动进入监听模式

**Comment by huiyadanli** [comment]
感谢你的建议，后续将添加该功能选项。
现在可以暂时用以下方法实现直接进入监听模式：

右键 PasteEx.exe 发送到 - 桌面快捷方式。
然后右键桌面快捷方式的**属性**，在目标后面空一格加上 **`monitor`** ，确定保存。
你可以把这个快捷方式扔在任何地方，并通过它直接进入监听模式。

![image](https://user-images.githubusercontent.com/15783049/46867070-4ed6a800-ce56-11e8-8856-7cea13867ecf.png)

**Comment by Little-Vicious** [comment]
Win10 下监听模式自动保存gif 火狐崩溃 谷歌无效

**Comment by huiyadanli** [comment]
> Win10 下监听模式自动保存gif 火狐崩溃 谷歌无效

@Little-Vicious 能否提供下GIF的来源页面？非监听模式下是否能够正常粘贴为文件？

**Comment by huiyadanli** [comment]
![clip_20181021](https://user-images.githubusercontent.com/15783049/47264193-fd0fdb00-d543-11e8-84ef-5b6188c95a55.png)
 v 1.1.7.4  已新增相关设置
