### ISSUE TITLE
自定义文本扩展名

### ISSUE THREAD

**Issue by yu037991** [huiyadanli/PasteEx#13]
自定义文本扩展名添加多种格式，有点不懂如何自定义的用户只有txt格式和html格式，比较难受

**Comment by huiyadanli** [comment]
自定义文本扩展名实际只是针对txt类型的文档改个扩展名，并且优先展示，你可以直接手动输入对应扩展名。。

**Comment by yu037991** [comment]
> 自定义文本扩展名实际只是针对txt类型的文档改个扩展名，并且优先展示，你可以直接手动输入对应扩展名。。

是我蠢了，没发现可以直接输入后缀格式
