### ISSUE TITLE
关于命名

### ISSUE THREAD

**Issue by yixuan10000** [huiyadanli/PasteEx#15]
能否剪贴板中前（10）多少个字符来命名，这样方便查找

**Comment by huiyadanli** [comment]
设置中把命名规则改成 `Clip_$yyyyMMdd$` 应该就能满足你的需求了。

这个规则是指以当前日期命名，你多次粘贴会出现重名，PasteEx 针对重名会自动往文件名后添加 (1) (2) 等等依次累加的数字编号
