### ISSUE TITLE
开机启动主界面体验

### ISSUE THREAD

**Issue by Zeroto521** [huiyadanli/PasteEx#16]
在设置为开机启动后，每次开机就会自动弹出提示。
可以对开机启动配置好的方式吗？

截图
> ![image](https://user-images.githubusercontent.com/25895405/47195949-e1180800-d390-11e8-82e6-734dc4c5264a.png)

**Comment by huiyadanli** [comment]
开机想要启动的是监听模式吧，可以按照 #12 中说的新建快捷方式，并把这个快捷方式放在启动文件夹中，就可以做到开机启动监听模式（不会弹出这个对话框）。

**Comment by Zeroto521** [comment]
我设置开机启动（新建快捷方式放到启动文件夹）后，每次开机都会弹出这个界面，挠头

**Comment by Zeroto521** [comment]
_(:з」∠)_
怎么说呢，可能**打开的姿势**不对吧。

**Comment by huiyadanli** [comment]
v 1.1.7.4 新增了 “默认开启监听模式” 的选项。。。可以尝试下。。对开机启动来说比较友好
