### ISSUE TITLE
锁定文件拓展名

### ISSUE THREAD

**Issue by wobunanguo0921** [huiyadanli/PasteEx#18]
希望可以在下一版本中新增一个锁定新建文件拓展名的选项，经常我希望复制的内容保存为txt文件，结果偶尔一不留神保存成了png格式。
感谢作者提供这么好用的软件！

**Comment by huiyadanli** [comment]
请问是从同一个地方（软件）复制的内容吗？

**Comment by wobunanguo0921** [comment]
是的，都是从Excel或者word中复制出来的片段文本，有时稍不注意就会默认保存为png

**Comment by huiyadanli** [comment]
新版本 [v 1.1.7.7](https://github.com/huiyadanli/PasteEx/releases/tag/1.1.7.7) 新增了选择扩展名历史记录的功能。

针对同一来源、童一剪切板格式类型，并选择了不同与 PasteEx 默认给出的扩展名选择列，将会自动记录选择的扩展名。

也就是说，你选择一次 txt 以后就默认使用 txt 格式保存了。

**Comment by wobunanguo0921** [comment]
感谢回复与改进升级，感谢huiyadanli提供如此便捷的程序！
