### ISSUE TITLE
关于开启监听后 图片.xxx（jpg/png）类型的自动后缀文件格式保存

### ISSUE THREAD

**Issue by triender** [huiyadanli/PasteEx#20]
把图片都保存为JPG格式需要怎么做呢

是不是这个设置
自定义文本扩展名规则
规则格式：扩展名=与此扩展名相对应文本的第一行特征（支持正则）
对于文本类型的文件，将会取第一个非空行对特征进行匹配， 匹配成功则在保存时默认使用对应的自定义扩展名。
比如：
cs=^using .*;$
java=^package.*;$
html=(?i)&lt;!DOCTYPE html
cpp=^#include.*

小白一点也不懂指令集，可以告诉我在自定义里需要添加什么指令规则吗，平常需要jpg格式的文件比较多。

谢谢您。

**Comment by huiyadanli** [comment]
自定义文本扩展名规则，只针对文本内容能够自定义扩展名。

暂时没有相关功能能够调整粘贴扩展名的顺序，你的需求和 #18 类似，都是调整默认粘贴扩展名顺序的。。

相关功能正在开发中，粘贴历史记录模块已经快开发完毕了，默认会优先使用上次选择的扩展名进行粘贴（针对于同一复制来源）。

**Comment by triender** [comment]
感谢回复与改进，谢谢您的改善工作。
