### ISSUE TITLE
命令行模式无法保存图片

### ISSUE THREAD

**Issue by Leoongithub** [huiyadanli/PasteEx#25]
使用命令行模式保存图片，会得到一个空文件。
另外希望增加一个不提示覆盖的命令行选项。

**Comment by huiyadanli** [comment]
刚刚我自己尝试了下的确是有问题。近期会修复这个问题并添加更多的配置项。
方便的话，能贴一下你使用的命令吗？

**Comment by Leoongithub** [comment]
使用的命令就是 `PasteEx /q location filename` 啊
除此以外，可以的话希望把这个和截图功能联系起来，比如截取某个指定区域或鼠标选取的区域并保存，或者截取全屏并保存。当然也希望能通过命令行调用。

**Comment by kunrui** [comment]
请问这个问题有解决了吗

**Comment by huiyadanli** [comment]
@Leoongithub @kunrui 
命令模式保存文件的问题已修复。可以暂时使用以下版本：

[PasteEx.v1.1.8.0.beta.zip](https://github.com/huiyadanli/PasteEx/files/3019072/PasteEx.v1.1.8.0.beta.zip)

使用 `PasteEx /qf location filename ` 命令保存图片，在图片重名时会强制覆盖。

最近比较忙，正式版本会晚些时候发布。

**Comment by huiyadanli** [comment]
[1.1.8.1](https://github.com/huiyadanli/PasteEx/releases/tag/1.1.8.1) 已经发布，完全重构了命令行参数。

具体使用方式参考[文档](https://github.com/huiyadanli/PasteEx/wiki#%E5%91%BD%E4%BB%A4%E8%A1%8C)。
