### ISSUE TITLE
复制的文本，也能自动保存。

### ISSUE THREAD

**Issue by peqing** [huiyadanli/PasteEx#28]
类似复制的图片自动保存一样，复制的文本也自动保存到《日期时间.txt》文件里，急需这个功能。谢谢您

**Comment by huiyadanli** [comment]
复制之后使用快捷键 `Ctrl + Alt + X`（默认）进行快速粘贴为文件，这个操作速度已经很快了。支持文本内容。

**Comment by peqing** [comment]
我知道，其实我主要是想保存剪贴板的历史纪录，用了其他几个软件，感觉都没您的好。

**Comment by huiyadanli** [comment]
Ditto 感觉很不错，我也在使用

**Comment by peqing** [comment]
比较喜欢用你的这个，简单轻便，DTTO太大了

**Comment by peqing** [comment]
大佬这个功能您能加么？

**Comment by huiyadanli** [comment]
这个功能有更加好的软件实现了。。。WIN10系统在1809更新后本身也自带了 Win + v 记录剪切板的功能。

未来可能会在插件化改造后，添加类似的功能。
