### ISSUE TITLE
提示窗口不在最上层

### ISSUE THREAD

**Issue by cooper1x** [huiyadanli/PasteEx#29]
![image](https://user-images.githubusercontent.com/9080789/56879817-f8952380-6a8c-11e9-94b6-63abdeb1c8b4.png)
如图所示，在qq界面点击文件上传，左边这个提示窗口在下面。

另外，如果点击保存之前复制了其他内容，那么点击保存后，就不再是之前的那个图片，这个地方看能不能优化下，是做个剪切板记录暂存还是什么，这个方面不是很懂，只是建议下。

**Comment by huiyadanli** [comment]
1. PasteEx 并没有强制置顶，置顶优先级可能也没有太高，不过可以考虑添加相关选项
2. 点击保存之前复制了其他内容这个问题。。我从一开始设计 PasteEx 的时候就处理了，应该不会被第二次复制覆盖，我测试了下也没有问题，有更加详细的复现过程么。。比如复制了什么类型的图片之类的。

**Comment by cooper1x** [comment]
我在保存之前，复制的是文本，这样好像就不行了。

**Comment by huiyadanli** [comment]
这个问题我确认过了，应该是不存在这种情况的，要不你再试试:joy:
