### ISSUE TITLE
Windows 10 蓝屏

### ISSUE THREAD

**Issue by Rovever** [huiyadanli/PasteEx#3]
打开软件的时候没有选择添加右键菜单，进入软件界面在设置里面添加的右键菜单， 用了不到一分钟就蓝屏了，系统是 win10 企业版 64 位。

**Comment by huiyadanli** [comment]
有没有更详细的蓝屏dump文件，或者蓝屏代码什么的。照理说，这个软件的行为应该都不怎么会和其他软件或者系统冲突引起蓝屏。

**Comment by huiyadanli** [comment]
PasteEx 本身就是在 win10 企业版 64 位 下开发的。
我在虚拟机里测试了下没出现你所说的问题。

PasteEx 平时是不常驻系统的，假如说你蓝屏时没启动它（右键 — 粘贴为文件），那应该跟 PasteEx 没啥关系。唯一的冲突可能是两个剪贴板工具同时使用，但是即便是同时使用，也不会出现蓝屏这种严重的系统错误。
