### ISSUE TITLE
希望可以加一个右键的按键

### ISSUE THREAD

**Issue by cooper1x** [huiyadanli/PasteEx#30]
我经常用这个，保存图片到一个临时目录，然后上传图片到论坛中。

如果有个按键，右键再按下字母，就会更快了，另外保存这个提示也可以省略掉，建议加个开关。

**Comment by huiyadanli** [comment]
原有保存的提示框出来以后按回车可以直接保存。。

设置里面有一个快速保存的右键菜单，可以不弹出提示框直接保存

**Comment by cooper1x** [comment]
好的，一段时间没用监听模式忘记了……

**Comment by huiyadanli** [comment]
额。。这不是监听模式的功能，本来就提供了一个快速粘贴的右键菜单来着。。
