### ISSUE TITLE
偶尔会出现.net报错

### ISSUE THREAD

**Issue by cooper1x** [huiyadanli/PasteEx#32]
![image](https://user-images.githubusercontent.com/9080789/68647383-baf37600-0558-11ea-94cf-d159eb7c2139.png)
这个我是在用snipaste截图的时候，偶尔会出现，之前以为是截图软件出问题了，仔细看了下弹窗和任务栏图标，发现是pasteex。
![image](https://user-images.githubusercontent.com/9080789/68647439-dcecf880-0558-11ea-8e80-dc150f051e17.png)
这个问题我不知道怎么排查，也不知道需要提供什么错误日志，先反馈一下。

**Comment by huiyadanli** [comment]
打开详细信息可以看到详细的错误。。
日志的话，就是`PasteEx.exe`同级目录中的的`User` 文件夹下的`PasteEx.log`，直接把 `PasteEx.log` 发给我就可以了

**Comment by cooper1x** [comment]
[PasteEx.exe.log](https://github.com/huiyadanli/PasteEx/files/3840669/PasteEx.exe.log)
这样可以吗？

**Comment by huiyadanli** [comment]
不是这个

是`User `文件夹下的`PasteEx.log`

![image](https://user-images.githubusercontent.com/15783049/68821419-3ffd9d00-06c9-11ea-9f1d-6462f1039244.png)

![image](https://user-images.githubusercontent.com/15783049/68821432-49870500-06c9-11ea-9f99-ec19368bf191.png)

**Comment by cooper1x** [comment]
[PasteEx.log](https://github.com/huiyadanli/PasteEx/files/3844465/PasteEx.log)
软件根目录下的吧，这个应该就是了。
