### ISSUE TITLE
添加一个使用scoop下载的方式

### ISSUE THREAD

**Issue by acdzh** [huiyadanli/PasteEx#34]
我为PasteEx写了一个scoop的App Manifests, 可以通过scoop来安装PasteEx.
`scoop install 'https://raw.githubusercontent.com/acdzh/zpt/master/bucket/pasteex.json'`

![image](https://user-images.githubusercontent.com/32260125/70424103-c67b8380-1aa9-11ea-916a-3994e22b55ef.png)

**Comment by huiyadanli** [comment]
感谢，已添加该安装方式到 README 中。

**Comment by acdzh** [comment]
thanks, 使用PasteEx也有一段时间了, 很喜欢这个小工具, 感谢. 
今天也算为它做了一点微小的贡献吧.

**Comment by snowman** [comment]
why not contribute to official repos
