### ISSUE TITLE
快速粘贴键在浏览器中无效

### ISSUE THREAD

**Issue by m1517** [huiyadanli/PasteEx#35]
你好, 感谢你开发的这个软件.
        我在浏览器中复制内容后,按快速粘贴键无效,必须切换出去才有效, 希望修复这个问题.我用的是360急速浏览器.win7系统.
      还有个建议,  将软件改成按下   快速粘贴键的快捷键(比如ctrl+g)     ,直接把选中的文本保存, 这样就不用先ctrl+c,再按快速粘贴, 更加便捷.  :)

**Comment by huiyadanli** [comment]
1. 快速粘贴必须要在一个资源管理器下使用（文件夹/桌面）。
2. 后续版本可能会加入此种功能
