### ISSUE TITLE
太强大了，是Paste Into File的 Pro version！请教

### ISSUE THREAD

**Issue by HAOOFE** [huiyadanli/PasteEx#36]
你好，我才发现你这个这么给力的工具，但是不幸我已经安装了Pasteintofile。 现在卡在不会怎么把它从我的右键菜单移除。。它的介绍是：
----
To remove the Paste Into File entry from the File Explorer context menu:
PasteIntoFile /unreg
----

请问这样就是我应该在powershell里头输入什么命令呢？我的文件在D:\Will\pasteIntoFile.exe。

先谢谢了，有了PasteEx，我实在没必要留着paste into file呀…

**Comment by huiyadanli** [comment]
Enter `D:\Will\pasteIntoFile.exe /unreg` directly in PowerShell, and press enter to execute. Administrator privileges may be required.

------------------

直接在 PowerShell 中输入 `D:\Will\pasteIntoFile.exe /unreg`，并回车执行就好了，可能会需要管理员权限。

**Comment by HAOOFE** [comment]
谢谢~按指导成功了~
