### ISSUE TITLE
能否为软件增加开机自启的设置，以配合监听模式长期使用

### ISSUE THREAD

**Issue by lint2** [huiyadanli/PasteEx#37]
当然，目前也可以手动添加自启动，但如果能像添加右键菜单一样方便就好了

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/118388242-d3fd4b80-b655-11eb-86e3-68341751aa73.png)

创建一个软件的快捷方式，并在后面添加 ` monitor`，双击打开就直接能够开启监听模式。

然后再把这个快捷方式复制到 启动 文件夹 (Win10 下该目录在 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`)

就能做到开机启动监听模式了。。

个人不太推荐监听模式常驻，可能会有很多兼容性问题。
