### ISSUE TITLE
建议简化粘贴为文件操作

### ISSUE THREAD

**Issue by xp44mm** [huiyadanli/PasteEx#39]
在某目录，从上下文菜单选择粘贴为文件后，建议直接用默认的文件名称，粘贴文件，不必弹出粘贴前的确认对话框。这和chrome浏览器下载文件的操作方式一致，可以事后再重命名文件。

**Comment by huiyadanli** [comment]
已经有这个功能了，设置页面添加 “快速粘贴为文件” 右键菜单项就可以使用

https://github.com/huiyadanli/PasteEx/wiki#%E5%BF%AB%E9%80%9F%E6%A8%A1%E5%BC%8F

**Comment by xp44mm** [comment]
原来是使用快捷键ctrl,alt,x，谢谢，早点问好了。

**Comment by huiyadanli** [comment]
> 原来是使用快捷键ctrl,alt,x，谢谢，早点问好了。

这个是更加快捷的方式。。但是需要软件常驻
