### ISSUE TITLE
1.0.1.8版本在关于页面的版本号还是1.0.1.5

### ISSUE THREAD

**Issue by DukeFox** [huiyadanli/PasteEx#4]
https://wx1.sinaimg.cn/large/006WkBxZgy1fmfafbd1dfj30gv0ed0t3.jpg

使用环境：
Win10 Pro 1709 x64, OS版本16299.98
已开系统的UAC，不过给了PasteEX管理员权限。

**Comment by huiyadanli** [comment]
已经修复 
[1.0.1.8.fix](https://github.com/huiyadanli/PasteEx/releases/tag/1.0.1.8)
