### ISSUE TITLE
出现问题导致停止工作

### ISSUE THREAD

**Issue by yuzlxt** [huiyadanli/PasteEx#40]
![图片_1](https://user-images.githubusercontent.com/42287503/103214236-dda64100-494a-11eb-8698-e94bd6f3607e.Png)
用来在用图片浏览器看图片的时候粘贴图片，图片有jpg和png格式。
开启了监控模式，可以复制之后直接ctrl+v在桌面粘贴成图片。但是有的图片不知道怎么回事突然就会导致停止工作。
一开始我看是jpg格式，以为jpg不能直接粘贴。就用右键粘贴成文件，但还是有问题。格式改成jpg也不行。
后来发现png格式的图片好像偶尔也会出错。我测试了一下感觉好像是图片的问题。
但是很奇怪，为什么有的jpg和png可以。有的不可以。图片都是同一个网站下的插画。
想问问是怎么回事,真的是某些图片不行吗？还是我哪里用错了。或者软件的问题。
谢谢。

**Comment by huiyadanli** [comment]
可以把日志发上来我看看
日志在程序 PasteEx.exe 同级目录中的的 User 文件夹下，名字叫PasteEx.log，直接把 PasteEx.log 发上来就可以了

**Comment by yuzlxt** [comment]
[PasteEx.log](https://github.com/huiyadanli/PasteEx/files/5750555/PasteEx.log)

**Comment by yuzlxt** [comment]
我看日志里似乎只有三条，昨天我也看过，就是这三条，但是实际出错次数已经很多次了。
不知道为什么没有其他的了。
我完全不懂，希望能指教一下到底是怎么回事。

**Comment by huiyadanli** [comment]
的确没相关日志，感觉像是软件冲突，程序直接挂了，连打印日志的机会都没有

是否有其他监听剪切板的软件也在同时运行？

**Comment by yuzlxt** [comment]
确实有，我还装了ditto,就是增强剪贴板的那个小软件，可以保存多条过去复制的内容。
但是之前没有特意注意过这两个软件的关系。
是因为这个软件吗？
还有，刚才不知道为什么，系统突然卡了，我在浏览器里点击，本来是当前页刷新的全都在新的标签页打开了。
然后发现其他软件也卡了，鼠标点不动。
然后我注销了一下，重新进入后，提示剪贴板无内容，是否还是要打开程序。才发现还是pasteEX的问题。
到底是怎么回事？难道真是软件冲突吗？
如果是的话，有办法解决吗？还是只能二选一？

**Comment by yuzlxt** [comment]
![图片_1](https://user-images.githubusercontent.com/42287503/103354212-ef701b80-4ae5-11eb-8074-0ef9f3956245.Png)

**Comment by huiyadanli** [comment]
> 确实有，我还装了ditto,就是增强剪贴板的那个小软件，可以保存多条过去复制的内容。
> 但是之前没有特意注意过这两个软件的关系。
> 是因为这个软件吗？
> 还有，刚才不知道为什么，系统突然卡了，我在浏览器里点击，本来是当前页刷新的全都在新的标签页打开了。
> 然后发现其他软件也卡了，鼠标点不动。
> 然后我注销了一下，重新进入后，提示剪贴板无内容，是否还是要打开程序。才发现还是pasteEX的问题。
> 到底是怎么回事？难道真是软件冲突吗？
> 如果是的话，有办法解决吗？还是只能二选一？

Ditto 是和 PasteEx的监控模式有冲突的，因为我也在使用 Ditto 所以提供了解决方案：[应用过滤](https://github.com/huiyadanli/PasteEx/wiki/App-Filter)

在 设置——应用过滤 中排除 Ditto 即可，相关 issue #11

**Comment by yuzlxt** [comment]
![图片_1](https://user-images.githubusercontent.com/42287503/103440484-0eef7b80-4c81-11eb-878e-00679fe8863b.Png)
![图片_2](https://user-images.githubusercontent.com/42287503/103440487-157df300-4c81-11eb-9933-23824eb2b224.Png)

**Comment by yuzlxt** [comment]
真是怪了，我在两个软件里都互相排除了。但是试了一下还是有问题。好像也没什么别的监听剪贴板的软件了啊。
装了listary，Wgestures鼠标手势之类的增强软件。还有rolan和天若OCR这些。但好像和剪贴板没太大关系吧。
刚才又试了试，基本就是jpg和png的图。一开始很正常。两种格式都可以。
但是碰到某个图之后就会直接崩溃。
重启软件后再用这个图试也会直接崩溃。感觉就是图的问题一样。
明明是同一种格式，难道有的图可以有的图就不行吗？
还是说还是因为软件和其他软件有什么冲突。

**Comment by yuzlxt** [comment]
![图片_3](https://user-images.githubusercontent.com/42287503/103440633-309d3280-4c82-11eb-909d-9eec4faa9691.Png)

**Comment by yuzlxt** [comment]
我试了试感觉好像就是图片的问题，奇怪的是哪怕是相同格式，相同风格，同一个作者的图片，有的好使，有的就会崩溃。
之前试过没问题的图片，复制多次也不会崩溃，但是一旦到了上次有问题的图片，马上就崩溃。
很奇怪，这是什么道理呢？我是个例还是说真的存在这种情况：
某些特定图片会直接导致程序崩溃。

**Comment by yuzlxt** [comment]
![65803473_p0](https://user-images.githubusercontent.com/42287503/103441081-7825bd80-4c86-11eb-9ef3-e4e7727e0864.jpg)
![65845161_p0](https://user-images.githubusercontent.com/42287503/103441085-7c51db00-4c86-11eb-8650-f40939260694.jpg)

**Comment by yuzlxt** [comment]
举个具体例子，上面两张插画，很容易看出是同一个作者的作品。都是我从pixiv上下载的，而且是一起下载的。
且都为jpg格式，但是，我在图片浏览器里按复制，在桌面按粘贴，
第一张图片可以正常的转为文件，png格式。
但是第二张图片，一粘贴程序就会直接崩溃。试几次都一样。
我是真的搞不懂了。
请问一下作者有什么头绪吗？

**Comment by huiyadanli** [comment]
是从 “图片浏览器” 复制的吗？这里的“图片浏览器”是什么软件？

如果是固定图片的话，可能跟图片有关系。

如果是在网页浏览器里复制的话，能提供下URL给我来复现试试？

如果可以是一直稳定复现这个问题的话，把方法提供给我，我来复现一次应该能找到问题所在

**Comment by yuzlxt** [comment]
图片浏览器是honeyview蜂蜜图片浏览器，不知道是不是跟它有关。
如果直接对图片复制粘贴的话，也就用不着pasteEX了。
我主要是为了浏览图片的时候，能直接按复制，直接粘贴到桌面好筛选出来。
为图片浏览器里面直接复制粘贴只能是到剪贴板。
问题可以稳定复现，就是某个特殊图片，只要一复制，不等粘贴，软件就会直接报错崩溃。
是一复制就出错。

**Comment by yuzlxt** [comment]
![65917135_p0](https://user-images.githubusercontent.com/42287503/103854185-d28da680-50ea-11eb-9c98-4eaec102a415.jpg)
![66089069_p0](https://user-images.githubusercontent.com/42287503/103854194-d6b9c400-50ea-11eb-9911-1ca3f9be2e44.jpg)

**Comment by yuzlxt** [comment]
这两张图片也是上两张同一个作者的。也是jpg格式，但是这两张没问题。可以正常复制。
唯一有问题的就是上面两张第二张，我刚才又试了。100%会出错。
一复制就崩溃。其他三张一点问题也没有。明明是同一作者，同一格式。
而且不只是这个作者的图片，其他风格的图片也是，有的好好的，有的就绝对会导致崩溃。

**Comment by huiyadanli** [comment]
我在Chrome浏览器里面复制上面两张图片没问题，我尝试下honeyview蜂蜜图片浏览器中的复制。

**Comment by huiyadanli** [comment]
> 我在Chrome浏览器里面复制上面两张图片没问题，我尝试下honeyview蜂蜜图片浏览器中的复制。

Honeyview 测试了下上面的图片也没有出现问题 😂

**Comment by yuzlxt** [comment]
:worried:啊，这 :broken_heart:
那就还是我电脑有什么问题了，是因为其他软件吗？
我是真没头绪了，还是我系统有啥问题？
怎么偏偏就会对特定的图片有反应呢？如果是跟其他软件冲突，应该直接就不好使吧。但是对别的图片就没问题。
我现在也不在乎能不能用了，我更好奇这到底是什么原因引起的，玄学一样:joy:

**Comment by huiyadanli** [comment]
大概率是图片的问题，PasteEx可能在图片转换的时候存在bug，在特定图片的情况下可能出现问题；
小概率是软件冲突的问题，多个剪切板软件多次操作剪切板出现的问题，可以控制变量法试试，比如说只保留一个软件运行看看是否出现问题。
