### ISSUE TITLE
无法识别盘符

### ISSUE THREAD

**Issue by lisansas** [huiyadanli/PasteEx#48]
如题，最新版本的pasteex无法识别盘符路径如（D:\ E:\），而会识别为桌面C:\user\admin\desktop 若是是D:\文件这种是可以识别的.

v1.1.7.8 Release是可以的。

我系统为win10 21H1

想到的几种可能性

pasteex的路径中有中文

qttabbar不兼容（但是1.1.7.8时我也装了 对了我是今天才更新的 已经重启过电脑）

**Comment by huiyadanli** [comment]
无法识别盘符具体是怎么样的表现？是在资源管理器中的 `D:\` 右键，点击粘贴为文件后，弹出来的主界面中没有定位到 `D:\` 吗？

**Comment by huiyadanli** [comment]
> 无法识别盘符具体是怎么样的表现？是在资源管理器中的 `D:\` 右键，点击粘贴为文件后，弹出来的主界面中没有定位到 `D:\` 吗？

我测试了下成功复现。。

**Comment by huiyadanli** [comment]
已修复，最新的版本可以从 https://github.com/huiyadanli/PasteEx/actions/runs/1075680221 下获取
