### ISSUE TITLE
能不能直接跟qq一样，不关心放在哪里

### ISSUE THREAD

**Issue by SiMaLaoShi** [huiyadanli/PasteEx#53]

**Comment by huiyadanli** [comment]
开启监听模式，自动图片转文件选项打开时，设置中的自动保存选项可以把所有复制的图片自动收集到指定文件夹。

https://github.com/huiyadanli/PasteEx/wiki#%E7%9B%91%E5%90%AC%E6%A8%A1%E5%BC%8F
