### ISSUE TITLE
[功能建议]不知道能不能添加xls或xlsx格式

### ISSUE THREAD

**Issue by xiaofan1991** [huiyadanli/PasteEx#56]
首先，我觉得现在默认的txt格式很好用，非常感谢！

我自己是学医的，不太会编程，我想知道能不能剪切板的内容直接导出为xls或xlsx文件，因为平常的实验数据基本还是用xlsx进行统计或汇报的，现在都是存成txt，再复制到xlsx这样，就是想一步到位，感觉就彻底完美了，不知道这个能不能实现

**Comment by huiyadanli** [comment]
程序上实现这个理论上是可以的。

前提是你复制的内容必须含有”表格“特征的情况
* 来源富文本类型（网页、文档等），复制后原始数据含有`<td>`等标签
* 来源于纯文本，复制后必须含有<kbd>Tab</kbd>符号

**不过非常抱歉，出于程序体积考虑，不会添加此类功能。** 一个Excel处理类库至少是当前 PasteEx 的几十倍大小。。。

当初设计的时候其实有考虑过PDF、压缩文件等等目标，后来因为体积问题否决了。

---

看到你的操作方式是 剪切板 -> txt -> excel

可以推测文本中应该是<kbd>Tab</kbd>符分割的。

可以直接利用txt2excel等软件、脚本直接批量转换成excel。
