### ISSUE TITLE
复制后，直接在指定目录生成文件

### ISSUE THREAD

**Issue by pjw20911** [huiyadanli/PasteEx#64]
复制文字后，自动在指定目录粘贴成文件。
免按键盘，免按鼠标，这样效率更高。

**Comment by huiyadanli** [comment]
emmm，这个类似自动图片转文件的功能。。

不过文字复制太庞杂了，自动文字转文件，更加难以筛选整理。

功能实现并不复杂，但是个人感觉没有必要。
