### ISSUE TITLE
复制没有后缀的文件时会报错

### ISSUE THREAD

**Issue by legendhill** [huiyadanli/PasteEx#67]
在打开监听模式后，复制没有后缀的文件时会报错
![1](https://user-images.githubusercontent.com/79631683/160224688-624f573f-d0f1-4bf6-afba-11efb1baaabb.png)

**Comment by legendhill** [comment]
我使用的资源管理器是Directory Opus，可能与这个有关

**Comment by huiyadanli** [comment]
不是，就是程序bug 😂 ，我加个判断就好

**Comment by huiyadanli** [comment]
直接在 Action 下载最新版 覆盖就能解决这个问题了 
https://github.com/huiyadanli/PasteEx/actions/runs/2043505238

**Comment by legendhill** [comment]
大佬，太感谢了！
