### ISSUE TITLE
开启自动图片转文件后，PowerPoint内粘贴行为异常

### ISSUE THREAD

**Issue by VictoriousRaptor** [huiyadanli/PasteEx#68]
如果开启了自动图片转文件，在PowerPoint内复制粘贴文本框、图形组合的时候，会把文本框、图形组合粘贴为图片

**Comment by huiyadanli** [comment]
这个涉及到PowerPoint对剪切板内容的判定。

![image](https://user-images.githubusercontent.com/15783049/166879520-9bfe9007-1708-437a-b654-4c5e506738e0.png)

只要把 POWERPNT 在 “设置—应用” 过滤中排除，就能解决这个问题。当然这么操作后， PasteEx监听模式下 的相关功能**针对 PowerPoint 复制操作** 也会处于不可用状态。个人感觉影响应该不大。

具体设置方式见：https://github.com/huiyadanli/PasteEx/wiki/App-Filter

**Comment by VictoriousRaptor** [comment]
可以了，非常感谢！
