### ISSUE TITLE
Can you translate wiki? this is hard to read.

### ISSUE THREAD

**Issue by ghost** [huiyadanli/PasteEx#71]
Can you translate wiki? this is hard to read.

**Comment by yfdyh000** [comment]
Have you tried some machine translation services and have specific difficulties?

**Comment by direrFlood** [comment]
Yes used google translate the code comments is not translated correctly

**Comment by huiyadanli** [comment]
PatesEx is very simple to use. Which function you want to know how to use ? Give me some screenshots and maybe I can answer your question.
