### ISSUE TITLE
通过todesk远程windows，在远程机中复制文本后弹出异常提示

### ISSUE THREAD

**Issue by maincooss** [huiyadanli/PasteEx#72]
![微信图片_20220822122830](https://user-images.githubusercontent.com/55976796/185839782-d27d8321-3f5b-418e-b435-825abdc66077.png)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Runtime.InteropServices.ExternalException (0x800401D0): 所请求的剪贴板操作失败。
   在 System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   在 System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   在 System.Windows.Forms.Clipboard.GetDataObject()
   在 PasteEx.Core.ClipboardData.Reload()
   在 PasteEx.Core.ModeController.ClipboardMonitor_OnClipboardChange(Object sender)
   在 PasteEx.Core.ClipboardMonitor.OnClipboardChangeEvent(Object sender)
   在 PasteEx.Core.ClipboardMonitor.ClipboardWatcher.ClipChanged(Object processId)
   在 PasteEx.Core.ClipboardMonitor.ClipboardWatcher.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4515.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PasteEx
    程序集版本:1.1.9.1
    Win32 版本:1.1.9.1
    基本代码:file:///D:/Program%20Files/PasteEx/PasteEx.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4515.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4536.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4395.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50

**Comment by huiyadanli** [comment]
两个软件同时操作剪切板产生了冲突。没有什么很好的解决方案，可以在PasteEx的设置中排除掉todesk相关进程。
