### ISSUE TITLE
pasteex into applications like discord?

### ISSUE THREAD

**Issue by ghost** [huiyadanli/PasteEx#73]
Hey,
Can we have pasteex paste files directly to applications instead of going down like this:
pasting to random directory
copying again
pasting again to the application(like discord)

**Comment by huiyadanli** [comment]
<img width="170" alt="Clip_20221016_200719" src="https://user-images.githubusercontent.com/15783049/196034596-c02659ab-eadc-433d-8772-fca172ab8f62.png">


Try start "Monitor Mode" and  check the "Auto Image to File".
When you copy any image, the clipboard will append the corresponding file contents, but the final result of pasting depends on the application.
