### ISSUE TITLE
开启监听后向Discord粘贴图片时会同时粘贴两项

### ISSUE THREAD

**Issue by VictoriousRaptor** [huiyadanli/PasteEx#76]
![图片](https://user-images.githubusercontent.com/10308169/202650904-4ab78747-9748-4614-8013-4bb82c298a4e.png)

如题，是Discord的问题吗？

**Comment by huiyadanli** [comment]
不是。
开启监听后，有个自动图片转文件的功能，这个功能会往原来剪切板中追加一个 图片的文件信息。此时剪贴板中既有图片信息，又有文件信息，有些软件比如Discord两项都解析了，就会产生这个问题。

**Comment by VictoriousRaptor** [comment]
> 不是。 开启监听后，有个自动图片转文件的功能，这个功能会往原来剪切板中追加一个 图片的文件信息。此时剪贴板中既有图片信息，又有文件信息，有些软件比如Discord两项都解析了，就会产生这个问题。

我描述有误，应该是开启自动文件转图片后才会有这种现象。除了关闭自动转文件以外，有没有办法可以避免这个问题？

**Comment by huiyadanli** [comment]
暂时没有其他方法了，除非再提供一个非追加直接替换剪切板内容的选项。

**Comment by VictoriousRaptor** [comment]
> 暂时没有其他方法了，除非再提供一个非追加直接替换剪切板内容的选项。

好的，感谢
