### ISSUE TITLE
你好，请教个问题~~

### ISSUE THREAD

**Issue by joylin1984** [huiyadanli/PasteEx#8]
版本1.0.3.5
用源码编译时，出现错误，filePaths 未定义，如图：
![devenv_2018-05-23_22-43-36](https://user-images.githubusercontent.com/13713368/40431920-00e82884-5edb-11e8-8dd2-dbce40329111.png)

本人初学菜鸟，望作者不吝赐教^ ^
1、请问为什么会出现这个错误？
2、if (Data.IAcquisition.GetData(DataFormats.FileDrop) is string[] filePaths) 这种语句没见过，请教了。

**Comment by huiyadanli** [comment]
今天做持续构建的时候恰巧遇到你这个问题。

这是 C# 7.0 一个叫做“模式匹配”的语法糖。VS2017 可以支持使用

```CSharp
 if (Data.IAcquisition.GetData(DataFormats.FileDrop) is string[] filePaths) { ... }
```

等同于

```CSharp
 string[] filePaths = Data.IAcquisition.GetData(DataFormats.FileDrop) as string[];
if (filePaths != null) { ... }
```

**Comment by joylin1984** [comment]
怪不得，谢了
