### ISSUE TITLE
[feature request] Convert photos to files in clipboard when pressing ctrl + alt + x

### ISSUE THREAD

**Issue by bigplayer-ai** [huiyadanli/PasteEx#80]
Hey,
can you Convert photos to files in clipboard when pressing ctrl + alt + x.
Meanwhile what I do:
copy pictures
paste the picture to desktop 
copy the files from the desktop again
paste the files again to the desired application.
Desired approach:
copy pictures
paste using ctrl + alt + x so the file version is pasted and not the image so applications can get the pictures as files.

**Comment by huiyadanli** [comment]
Just use `Auto Image to File` for your needs

<img width="138" alt="Clip_20230127_140121" src="https://user-images.githubusercontent.com/15783049/215019940-6c1f208e-dd6d-4617-bcf9-8144bfcfdb87.png">

If this feature is enabled, the clipboard will automatically append a file type to the image file when you copy an image. But when you paste it into other software, whether the other software resolves it to a file type or a picture type depends on how the developer of the software resolves the clipboard。

**Comment by bigplayer-ai** [comment]
Why when I copy an image file to application, the application resolves it as an image file.But when pasting the imade directly using pasteex, the application resolves it as an image.On 27 Jan 2023, at 8:08, 辉鸭蛋 ***@***.***> wrote:﻿
Just use Auto Image to File for your needs

If this feature is enabled, the clipboard will automatically append a file type to the image file when you copy an image. But when you paste it into other software, whether the other software resolves it to a file type or a picture type depends on how the developer of the software resolves the clipboard。

**Comment by huiyadanli** [comment]
Each software handles the content of the clipboard differently. I can't control how other software handles the clipboard.
