### ISSUE TITLE
使用shell脚本执行命令，是否可以返回生成的文件路径与文件名？

### ISSUE THREAD

**Issue by kunrui** [huiyadanli/PasteEx#81]
目前使用shell脚本执行如下命令：
```
PasteEx.exe -q -f "c:\tmp\"
```
希望可以返回生成的文件名，方便后续其它程序使用。

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/PasteEx/commit/34e2e9b296a6eb1bd05f980ce6fede0fe79f0322 已经改造

试试最新的编译版本: [actions](https://github.com/huiyadanli/PasteEx/actions/runs/4021974987)
