### ISSUE TITLE
您好，可否增加全局快捷键，按全局快捷键可快速保存至指定位置。指定位置可否支持相对路径？谢谢您。

### ISSUE THREAD

**Issue by houxiren** [huiyadanli/PasteEx#9]
您好，可否增加全局快捷键，按全局快捷键可快速保存至指定位置。指定位置可否支持相对路径？谢谢您。

谢谢开发如此好软件！祝开发者越来越好！

**Comment by huiyadanli** [comment]
新版本 [v1.1.6.7](https://github.com/huiyadanli/PasteEx/releases/tag/1.1.6.7) 新增的 [监听模式](https://github.com/huiyadanli/PasteEx/wiki#%E7%9B%91%E5%90%AC%E6%A8%A1%E5%BC%8F) 可以满足你的要求。
