### ISSUE TITLE
监听排除列表失效

### ISSUE THREAD

**Issue by VictoriousRaptor** [huiyadanli/PasteEx#90]
![image](https://github.com/huiyadanli/PasteEx/assets/10308169/b1a627ec-1d5f-4dc8-ac88-79d4df07b89e)

开启监听和自动图片转文件并将Excel加入排除列表，复制单元格，在微信、GitHub网页等输入框中粘贴，仍然会粘贴为图片格式，例如：

![Clip_20230609_100205](https://github.com/huiyadanli/PasteEx/assets/10308169/1bcd18c4-59ba-484a-8815-bc5d9897c49f)

**Comment by huiyadanli** [comment]
你把PasteEx关掉，应该也是一样的。

因为excel复制的时候会向剪切板写入文本+图片，至于粘贴成文件还是图片，就要看其他编辑器如何处理剪切板内同时存在文本+图片的情况。有些优先粘贴图片，有些只能粘贴文本

**Comment by VictoriousRaptor** [comment]
> 你把 PasteEx 关掉，应该也是一样的。已经和 PasteEx 无关了
> 
> 因为excel复制的时候会向剪切板写入文本+图片，至于粘贴成文件还是图片，就要看其他编辑器如何处理剪切板内同时存在文本+图片的情况。有些优先粘贴图片，有些只能粘贴文本

确实无关，不好意思，我有点想当然了
